### ISSUE TITLE
kueken7_bgr8_srgb.dds has a wrong format header

### ISSUE THREAD

**Issue by elect86** [g-truc/gli#78]
It reads `DXGI_FORMAT_B8G8R8X8_UNORM_SRGB` but it should be `DXGI_FORMAT_B8G8R8_SRGB_GLI` instead

**Comment by Groovounet** [comment]
My guess is that his file actually store DXGI_FORMAT_B8G8R8X8_UNORM_SRGB.

"DXGI_FORMAT_B8G8R8_SRGB_GLI" is really just a GLI extension, so that the file would have to be saved with GLI.

I notice that the tools I have been using were actually saving to a different format they claimed saving. I have been doing some cleaning and this one sounds like a left over.

Thanks,
Christophe
