### ISSUE TITLE
kueken7_la8_unorm.dds fires FORMAT_INVALID

### ISSUE THREAD

**Issue by elect86** [g-truc/gli#80]
Load_dds doesn't handle it properly

Ps: is this [`kueken7_rg11b10_ufloat.dds`](http://imgur.com/VOvQlzW) rendered right?

**Comment by Groovounet** [comment]
Both files are broken due to PVRtexTool bugs that I used to generate the files.

Thanks to the new gli::convert function, I generated updated files for kueken7_rg11b10_ufloat.dds and kueken7_rg11b10_ufloat.ktx.

kueken7_la8_unorm.dds is broken too. GLI still doesn't have code to copy textures with different channels. I am just going to remove that file.

**Comment by Groovounet** [comment]
Done, thanks for contributing!
Christophe

**Comment by elect86** [comment]
`kueken7_rgb5a1_unorm_.dds` also
